# Generated by Django 4.2.1 on 2023-05-30 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0010_alter_cartitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
    ]
