# Generated by Django 4.2.1 on 2023-06-01 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store_app', '0016_remove_cartitem_session_key_cartitem_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_checkout_price', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('payment_type', models.CharField(max_length=10)),
                ('cartitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.cartitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
