# Generated by Django 4.2.1 on 2023-06-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0017_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='total_checkout_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
