# Generated by Django 4.2.1 on 2023-06-01 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0018_alter_checkout_total_checkout_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='cartitem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store_app.cartitem'),
        ),
    ]
