# Generated by Django 4.2.1 on 2023-06-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0025_address_order_orderitem_delete_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='district',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='payment_type',
            field=models.CharField(default='1', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(default='1', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='place',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='total_checkout_price',
            field=models.DecimalField(decimal_places=2, default='1', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(max_length=200),
        ),
    ]
