# Generated by Django 4.2.1 on 2023-06-01 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0026_address_district_address_name_address_payment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='delivary_address',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='store_app.address'),
            preserve_default=False,
        ),
    ]
