# Generated by Django 4.2.1 on 2023-06-01 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0028_address_orderitem_alter_orderitem_delivary_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='orderitem',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='delivary_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.address'),
        ),
    ]
