# Generated by Django 4.2.1 on 2023-06-06 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0029_remove_address_orderitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='product',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='store_app.mobilepouch'),
            preserve_default=False,
        ),
    ]
