# Generated by Django 4.2.1 on 2023-06-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0030_address_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='quantity',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
