# Generated by Django 4.2.1 on 2023-06-06 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0031_address_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='product',
        ),
        migrations.RemoveField(
            model_name='address',
            name='quantity',
        ),
    ]
